// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returns the value of the indexed component in the specified array object.
 */
public class ArrayGet extends CustomJavaAction<IMendixObject>
{
	private java.util.List<IMendixObject> array;
	private java.lang.Long index;

	public ArrayGet(IContext context, java.util.List<IMendixObject> array, java.lang.Long index)
	{
		super(context);
		this.array = array;
		this.index = index;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.index >= this.array.size()){
			return null;
		}
		return this.array.get(new Long(this.index).intValue());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ArrayGet";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
