// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Return a list with only objects from a given specialisation
 */
public class ArrayFilterOnSpecialisation extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.util.List<IMendixObject> array;
	private java.lang.String specialisation;

	public ArrayFilterOnSpecialisation(IContext context, java.util.List<IMendixObject> array, java.lang.String specialisation)
	{
		super(context);
		this.array = array;
		this.specialisation = specialisation;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> resultList = new ArrayList<IMendixObject>();
		if (this.array != null){
			for (IMendixObject object : this.array){
				if (object.getType().equals(this.specialisation)){
					resultList.add(object);
				}
			}
		}
		return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ArrayFilterOnSpecialisation";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
