// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class CascadeCommit extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject anyObject;
	private java.lang.String entityFilter;

	public CascadeCommit(IContext context, IMendixObject anyObject, java.lang.String entityFilter)
	{
		super(context);
		this.anyObject = anyObject;
		this.entityFilter = entityFilter;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		new FilteredCascadeCommit(this.entityFilter, this.getContext()).cascadeCommit(anyObject);		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CascadeCommit";
	}

	// BEGIN EXTRA CODE
	
	// END EXTRA CODE
}
