// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import com.mendix.core.objectmanagement.member.MendixHashString;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;

public class CompareHashedString extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject hashedStringObject;
	private java.lang.String hashedStringAttribute;
	private java.lang.String unhashedValue;

	public CompareHashedString(IContext context, IMendixObject hashedStringObject, java.lang.String hashedStringAttribute, java.lang.String unhashedValue)
	{
		super(context);
		this.hashedStringObject = hashedStringObject;
		this.hashedStringAttribute = hashedStringAttribute;
		this.unhashedValue = unhashedValue;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMendixObjectMember<?> hashedValue = this.hashedStringObject.getMember(this.getContext(), this.hashedStringAttribute);
		if (hashedValue instanceof MendixHashString){
			MendixHashString hashString = (MendixHashString ) hashedValue;
			return hashString.verifyValue(this.getContext(), this.unhashedValue);
		}
		return false;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CompareHashedString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
