// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CreateObject extends CustomJavaAction<IMendixObject>
{
	private IMendixObject ObjectType;

	public CreateObject(IContext context, IMendixObject ObjectType)
	{
		super(context);
		this.ObjectType = ObjectType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMendixObject mendixObject = Core.instantiate(getContext(), this.ObjectType.getType());
		return mendixObject;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
