// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.webui.CustomJavaAction;
import jamcommons.proxies.Singleton;
import jamcommons.proxies.SingletonFileDocument;
import jamcommons.proxies.SingletonImage;

public class CreateSingletonInstances extends CustomJavaAction<java.lang.Boolean>
{
	public CreateSingletonInstances(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMetaObject metaObjectSingleton = Core.getMetaObject(Singleton.entityName);
		IMetaObject metaObjectSingletonFileDocument = Core.getMetaObject(SingletonFileDocument.entityName);
		IMetaObject metaObjectSingletonImage = Core.getMetaObject(SingletonImage.entityName);

		List<IMetaObject> subObjects = new ArrayList<IMetaObject>();
		for (IMetaObject metaObject : metaObjectSingleton.getSubObjects()) {
			subObjects.add(metaObject);
		}

		for (IMetaObject metaObject : metaObjectSingletonFileDocument.getSubObjects()) {
			subObjects.add(metaObject);
		}

		for (IMetaObject metaObject : metaObjectSingletonImage.getSubObjects()) {
			subObjects.add(metaObject);
		}

		for (IMetaObject subObject : subObjects) {
			List<IMendixObject> mxObjects = Core.retrieveXPathQuery(getContext(), "//" + subObject.getName());

			if (mxObjects.size() > 1) {
				Core.delete(getContext(), mxObjects);
				mxObjects.clear();
			}

			if (mxObjects.size() == 0) {
				IMendixObject mendixObject = Core.instantiate(getContext(), subObject.getName());
				Core.commit(getContext(), mendixObject);
			}
		}

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateSingletonInstances";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
