// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import java.awt.image.BufferedImage;
import java.io.InputStream;
import javax.imageio.ImageIO;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * Return the height of an image
 * 
 * Use GetImageDimensions from community commons
 */
public class DepricatedGetImageHeight extends CustomJavaAction<java.lang.Long>
{
	private IMendixObject __image;
	private system.proxies.Image image;

	public DepricatedGetImageHeight(IContext context, IMendixObject image)
	{
		super(context);
		this.__image = image;
	}

	@Override
	public java.lang.Long executeAction() throws Exception
	{
		this.image = __image == null ? null : system.proxies.Image.initialize(getContext(), __image);

		// BEGIN USER CODE
		if (this.image.getHasContents(getContext())){
			InputStream imageInputStream = Core.getImage(getContext(), this.image.getMendixObject(), false);			
			BufferedImage bufferedImage = ImageIO.read(imageInputStream);
			return Integer.valueOf(bufferedImage.getHeight()).longValue();
		}
		return 0l;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "DepricatedGetImageHeight";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
