// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.servlet.http.HttpServletResponse;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import jamcommons.proxies.Header;

public class RetrieveResponseHeaders extends CustomJavaAction<java.util.List<IMendixObject>>
{
	public RetrieveResponseHeaders(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE

		List<IMendixObject> result = new ArrayList<IMendixObject>();

		Optional<IMxRuntimeResponse> runtimeResponseOptional = super.getContext().getRuntimeResponse();
		if (runtimeResponseOptional.isPresent()) {
			IMxRuntimeResponse runtimeResponse = runtimeResponseOptional.get();
			HttpServletResponse httpServletResponse = runtimeResponse.getHttpServletResponse();
			for (String headerKey : httpServletResponse.getHeaderNames()) {
				Header header = new Header(super.getContext());
				header.setKey(headerKey);
				header.setValue(httpServletResponse.getHeader(headerKey));
				result.add(header.getMendixObject());
			}
		}

		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveResponseHeaders";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
