// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Round a value to the nearest value possible by the multiplier.
 */
public class RoundByMultiple extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Long value;
	private java.lang.Long multiplier;

	public RoundByMultiple(IContext context, java.lang.Long value, java.lang.Long multiplier)
	{
		super(context);
		this.value = value;
		this.multiplier = multiplier;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return new nl.jam.mendix.library.lib.RoundByMultiple().roundByMultiple(value, multiplier);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RoundByMultiple";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
