// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import com.ibm.icu.util.ULocale;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import nl.jam.mendix.library.lib.SpelloutNumbers;

/**
 * The locale string for Dutch is 'nl_NL' which will format numbers as 'duizendnegenhonderdvierenvijftig', to use the inverse notation ('negentienhonderdvierenvijftig') you can use the locale 'nl_NL_Inverse'.
 */
public class SpelloutNumber extends CustomJavaAction<java.lang.String>
{
	private java.lang.String locale;
	private java.math.BigDecimal number;

	public SpelloutNumber(IContext context, java.lang.String locale, java.math.BigDecimal number)
	{
		super(context);
		this.locale = locale;
		this.number = number;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Remove soft hyphen's because they are returned as hard hyphens by mendix after retrieving a string value from a attribute
		return new SpelloutNumbers(this.locale).format(this.number).replaceAll("\u00AD", "");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SpelloutNumber";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
