// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jamcommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Clean a string by:
 * - Trimming
 * - Remove control characters
 * - Remove non-printable characters
 */
public class StringClean extends CustomJavaAction<java.lang.String>
{
	private java.lang.String inputString;

	public StringClean(IContext context, java.lang.String inputString)
	{
		super(context);
		this.inputString = inputString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return this.inputString.trim().replaceAll("\\p{C}", "") // replace ASCII control characters
				.replaceAll("\\p{Cntrl}", "") // replace ASCII control characters
				.replaceAll("\\p{Cc}", "") // replace ASCII control characters
				.replaceAll("[^\\p{Print}]", ""); // replace all ASCII non-printable characters
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringClean";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
